# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TrainToChangi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrainToChangi
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'

  target 'TrainToChangiTests' do
    inherit! :search_paths
    pod 'Firebase'
    pod 'SwiftLint'
    # Pods for testing
  end

end
